// <auto-generated />
using System;
using Ejercicio.Infraestructura.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ejercicio.Infraestructura.Datos.Migrations
{
    [DbContext(typeof(ContextoAccesoDatos))]
    [Migration("20210312230642_CreacionBD")]
    partial class CreacionBD
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ejercicio.Dominio.Entidades.Articulo", b =>
                {
                    b.Property<string>("CodigoArticulo")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NombreArticulo")
                        .IsRequired();

                    b.Property<decimal>("PrecioArticulo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("StockArticulo");

                    b.HasKey("CodigoArticulo");

                    b.ToTable("Articulo");
                });

            modelBuilder.Entity("Ejercicio.Dominio.Entidades.Cliente", b =>
                {
                    b.Property<long>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApellidoCliente")
                        .IsRequired();

                    b.Property<string>("NombreCliente")
                        .IsRequired();

                    b.HasKey("IdCliente");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("Ejercicio.Dominio.Entidades.Orden", b =>
                {
                    b.Property<long>("IdOrden")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FechaOrden");

                    b.Property<long>("IdCliente");

                    b.HasKey("IdOrden");

                    b.HasIndex("IdCliente");

                    b.ToTable("Orden");
                });

            modelBuilder.Entity("Ejercicio.Dominio.Entidades.OrdenArticulo", b =>
                {
                    b.Property<string>("CodigoArticulo");

                    b.Property<long>("IdOrden");

                    b.Property<long>("CantidadArticulo");

                    b.HasKey("CodigoArticulo", "IdOrden");

                    b.HasIndex("IdOrden");

                    b.ToTable("OrdenArticulo");
                });

            modelBuilder.Entity("Ejercicio.Dominio.Entidades.Orden", b =>
                {
                    b.HasOne("Ejercicio.Dominio.Entidades.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Ejercicio.Dominio.Entidades.OrdenArticulo", b =>
                {
                    b.HasOne("Ejercicio.Dominio.Entidades.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("CodigoArticulo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ejercicio.Dominio.Entidades.Orden")
                        .WithMany("OrdenArticulos")
                        .HasForeignKey("IdOrden")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
